//TODO*** Work on the interests list and splitting / sorting...
//TODO*** Fix so that when a post is liked or unliked it updates automatically
//TODO*** Work on Alert system - Needs better implementation to avoid "screen bumping"